q=["Where is Germany?",
   "Where is England?",
   "Name the person who was also khown as DESHABANDHU.",
   "The capital of Uttarakhand is",
   "Who is the richest man in the world?",
   "Panini was",
   "Which of the following is the largest and the deepest ocean of the world?",
   "SAARC was formed in ",
   "When India national football team was established?",
   "The first speaker of Lok Sabha was",
   "Mount Etna is a famous volcano located in...",
   "Reserve Bank of India is headquartered at..",
   "When Earth Day observed world wide in 2017?",
   "This country is known as the Sugar Bowl of the World, Identify it from the given options.",]


o=[["In Europe","In Great Britain","In Asia","In the USA"],
   ["In Asia","On an island","In the USA","In China"],
   ["S.Radhakrishnan","G.K.Gokhale","Chittaranjan Das","Madan Mohan Malviya"],
   ["Masoorie","Dehra Dun","Nainital","None of these"],
   ["Jeff Bezos","Bill Gates","Donald Trump","Mark Zuckerberg"],
   ["a Greek philosopher","an Indian astronomer and famous mathematician","a Sanskrit grammarian of Vedic times","great poet of ancient times."],
   ["Arctic"," Atlantic","Pacific","Indian"],
   ["1982","1984","1985","1986"],
   ["1937","1938","1940","1952"],
   [" K.M. Munshi"," C.D. Deshmukh","G.V. Mavalankar","H.J. Kania"],
   ["Argentina","Italy"," Mexico","Philipines"],
   [" Kolkata","New Delhi","Mumbai","Chennai"],
   ["April 22, 2017"," April 24, 2018","April 25, 2018","April 21, 2017"],
   [" Brazil","Cuba","Mexico","Algeria"]]


a=["In Europe",
   "On an island",
   "Chittaranjan Das",
   "Dehra Dun",
   "Jeff Bezos",
   " a Sanskrit grammarian of Vedic times",
   "Pacific",
   "1985",
   "1937",
   "G.V. Mavalankar",
   "Italy",
   "Mumbai",
   "April 22, 2017",    
   "Cuba"]
